/**
 * Utilities to manage promotions and school years
 * School year: August 25 of N to August 24 of N+1
 */

/**
 * Gets the school year of a given date
 * @param date - Date to analyze
 * @returns The year N of the school year (August 25 of N to August 24 of N+1)
 */
export function getSchoolYear(date: Date): number {
	const month = date.getMonth() + 1; // 1-12
	const year = date.getFullYear();

	if (month < 8 || (month === 8 && date.getDate() < 25)) {
		return year - 1;
	}

	return year;
}

/**
 * Computes the default applicable Promo tags for a date
 * Includes the current promo and the 3 previous promotions
 * @param date - Album date
 * @returns Array of Promo tags (e.g. ['Promo 2025', 'Promo 2024', 'Promo 2023', 'Promo 2022'])
 */
export function getDefaultPromoTags(date: Date): string[] {
	const schoolYear = getSchoolYear(date);
	const tags: string[] = [];

	for (let i = 0; i < 4; i++) {
		tags.push(`Promo ${schoolYear - i}`);
	}

	return tags;
}

/**
 * Formats an array of tags into a comma-separated string
 * @param tags - Array of tags
 * @returns Formatted string: "Tag1, Tag2, Tag3"
 */
export function formatTagsToString(tags: string[]): string {
	return tags.join(', ');
}

/**
 * Parses a tag string into an array
 * @param tagsString - Comma-separated tag string
 * @returns Array of trimmed and filtered tags
 */
export function parseTagsFromString(tagsString: string): string[] {
	return tagsString
		.split(',')
		.map((t) => t.trim())
		.filter((t) => t.length > 0);
}

/**
 * Checks whether a tag string contains only auto-generated tags (Promo XXXX)
 * @param tagsString - Tag string
 * @returns true if all tags are of the form "Promo XXXX"
 */
export function isOnlyAutoGeneratedTags(tagsString: string): boolean {
	if (!tagsString.trim()) {
		return true;
	} // Empty is considered "auto-generated"

	const tags = parseTagsFromString(tagsString);
	return tags.every((tag) => /^Promo \d{4}$/.test(tag));
}
