/**
 * Utilitaires pour gérer les promotions et les années scolaires
 * Année scolaire: 25 août N au 24 août N+1
 */

/**
 * Obtient l'année scolaire d'une date donnée
 * @param date - Date à analyser
 * @returns L'année N de l'année scolaire (25 août N au 24 août N+1)
 */
export function getSchoolYear(date: Date): number {
	const month = date.getMonth() + 1; // 1-12
	const year = date.getFullYear();

	if (month < 8 || (month === 8 && date.getDate() < 25)) {
		return year - 1;
	}

	return year;
}

/**
 * Calcule les tags Promo applicables par défaut pour une date
 * Inclut la promo actuelle et les 3 promotions précédentes
 * @param date - Date de l'album
 * @returns Array de tags Promo (ex: ['Promo 2025', 'Promo 2024', 'Promo 2023', 'Promo 2022'])
 */
export function getDefaultPromoTags(date: Date): string[] {
	const schoolYear = getSchoolYear(date);
	const tags: string[] = [];

	for (let i = 0; i < 4; i++) {
		tags.push(`Promo ${schoolYear - i}`);
	}

	return tags;
}

/**
 * Formate un tableau de tags en string séparée par des virgules
 * @param tags - Array de tags
 * @returns String formatée: "Tag1, Tag2, Tag3"
 */
export function formatTagsToString(tags: string[]): string {
	return tags.join(', ');
}

/**
 * Parse une string de tags en tableau
 * @param tagsString - String des tags séparés par des virgules
 * @returns Array de tags trimés et filtrés
 */
export function parseTagsFromString(tagsString: string): string[] {
	return tagsString
		.split(',')
		.map((t) => t.trim())
		.filter((t) => t.length > 0);
}

/**
 * Vérifie si une string de tags ne contient que des tags auto-générés (Promo XXXX)
 * @param tagsString - String des tags
 * @returns true si tous les tags sont de la forme "Promo XXXX"
 */
export function isOnlyAutoGeneratedTags(tagsString: string): boolean {
	if (!tagsString.trim()) {
		return true;
	} // Empty is considered "auto-generated"

	const tags = parseTagsFromString(tagsString);
	return tags.every((tag) => /^Promo \d{4}$/.test(tag));
}
