/**
 * Stand-in for SvelteKit's `$env/dynamic/private` under vitest.
 *
 * The runtime module is generated by `svelte-kit sync` and only resolves inside a SvelteKit build,
 * so importing any server module that reads configuration would fail here on the import alone -
 * which is why `src/lib/auth.ts` had no unit test at all. Nothing in this stub is a fixture: the
 * tests that reach it exercise code paths that never read `env`, and an empty object makes that
 * explicit by breaking loudly if one ever does.
 */
export const env: Record<string, string | undefined> = {};
